name: Fraud Detection Automation

on:
  push:
    paths:
      - "new_transactions.csv"
      - "fraud_detector.py"
      - "fraud_model.joblib"

jobs:
  detect-fraud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Fraud Detector Script
      run: |
        python fraud_detector.py

    - name: Upload Predictions Result
      uses: actions/upload-artifact@v4
      with:
        name: fraud_predictions
        path: predictions.csv
